# Generated by Django 6.0.4 on 2026-04-17 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/')),
                ('estado', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('has_premium', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(max_length=100)),
                ('payload_json', models.JSONField()),
                ('leido', models.BooleanField(default=False)),
                ('user_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(choices=[('pelicula', 'pelicula'), ('libro', 'libro'), ('lugar', 'lugar'), ('serie', 'serie'), ('otro', 'otro')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recomendaciones/imagenes/')),
                ('enlace_externo', models.URLField(blank=True, max_length=500, null=True)),
                ('visibilidad', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=20)),
                ('estado', models.CharField(choices=[('creado', 'creado'), ('eliminado', 'eliminado')], default='creado', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('expirada', 'expirada'), ('cancelada', 'cancelada')], default='activa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('transaccion_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('blocked', 'blocked'), ('removed', 'removed'), ('rejected', 'rejected')], max_length=20)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amistades',
                'constraints': [models.CheckConstraint(condition=models.Q(('usuario', models.F('amigo')), _negated=True), name='amistad_distintos_usuarios')],
            },
        ),
        migrations.CreateModel(
            name='RankingAgregado',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_score', models.IntegerField(default=0)),
                ('total_reacciones', models.IntegerField(default=0)),
                ('avg_score_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_agregado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ranking_agregado',
                'constraints': [models.CheckConstraint(condition=models.Q(('total_score__gte', 0)), name='ranking_total_score_gte_0'), models.CheckConstraint(condition=models.Q(('total_reacciones__gte', 0)), name='ranking_total_reacciones_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stars', models.SmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('visto', 'visto'), ('aceptado', 'aceptado'), ('rechazado', 'rechazado')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to=settings.AUTH_USER_MODEL)),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='api.recomendacion')),
            ],
            options={
                'db_table': 'reacciones',
                'constraints': [models.CheckConstraint(condition=models.Q(('stars__gte', 0), ('stars__lte', 5)), name='reaccion_stars_0_5'), models.UniqueConstraint(fields=('recomendacion', 'user'), name='unica_reaccion_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('creado', 'creado'), ('eliminado', 'eliminado')], default='creado', max_length=20)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to=settings.AUTH_USER_MODEL)),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recomendacion')),
            ],
            options={
                'db_table': 'compartidos',
                'unique_together': {('receptor', 'recomendacion')},
            },
        ),
    ]
